name: 'Install packages'
description: 'Install additional GAP packages'

inputs:
  packages:
    description: 'Space-separated or newline-separated list of packages to install'
    required: true
    default: ''

runs:
  using: "composite"
  steps:

    - name: Install bsdtar
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends libarchive-tools

    - name: Install GAP packages
      shell: bash
      run: |
        # Convert newlines to spaces
        PACKAGES=$(echo "${{ inputs.packages }}" | tr '\n' ' ')
     
        if [[ "${RUNNER_OS}" = "Windows" ]]; then
          TMPDIR=$(cygpath -u "${RUNNER_TEMP}/install-pkg")
        else
          TMPDIR="${RUNNER_TEMP}/install-pkg"
        fi
        
        mkdir -p "${TMPDIR}"
        DEST="${GAPROOT}/pkg"
        PKG_DISTRO="${TMPDIR}/package-infos.json"
        
        # Needed to get reasonable API limits
        WGET_HEADER="Authorization: token ${{ github.token }}"

        # Load helper functions
        source "${GITHUB_ACTION_PATH}/install-pkg-functions.sh"
        
        for pkg in ${PACKAGES}; do
          echo "::group::Installing ${pkg}"
          
          version="latest"
          repo=""
          distro_ver=""

          # Split off version, if present
          if [[ "${pkg}" == *@* ]]; then
            version="${pkg##*@}"
            pkg="${pkg%@*}"
          fi

          # Set the $name variable
          get_pkg_name "${pkg}"
          pkgdir="${DEST}/${name}"

          if [[ "${pkg}" =~ ^https?://.*\.(tar\.gz|tar\.bz2|zip)$ ]]; then
            echo "Input is an archive"
            download_and_extract "${pkg}" "${pkgdir}"
          else
            use_repo=true
            if [[ "${pkg}" =~ .*/.* ]]; then
              echo "Input is a package repository"
              repo="${pkg}"
            else
              echo "Input is a package name"
              get_pkg_info_from_name "${name}"
              echo "Package distribution contains version ${distro_ver}"
              # If the desired version is the one available in the package distribution,
              # we use the info there instead of going to the package repository
              if [[ "${version}" = "latest" ]] || [[ "${version}" = "${distro_ver}" ]]; then
                echo "Using package distribution"
                version="${distro_ver}"
                use_repo=false
              else
                echo "Using repository ${repo}"
              fi
            fi

            if [[ "${version}" = "devel" ]]; then
              echo "Cloning development branch of ${repo} to ${pkgdir}"
              clear_dest "${pkgdir}"
              git clone -q --depth=1 --single-branch "https://github.com/${repo}.git" "${pkgdir}"
            else
              # Update the $archive_url and $version variables
              if [[ ${use_repo} = true ]]; then
                echo "Getting archive url from repository"
                get_archive_url "${repo}" "${version}"
              fi
              
              # Check if package version is already available
              if check_pkg_availability "${name}" "${version}"; then
                  echo "Package ${name} ${version} is already available, skipping."
                  continue
              fi

              download_and_extract "${archive_url}" "${pkgdir}"
            fi
          fi
        done
